### ISSUE TITLE
Build markdown template to host future course sites

### ISSUE THREAD

**Issue by maabernethy** [maabernethy/jake-academic-site#5]
Can link to current course sites, but future ones would ideally be local markdown files

**Comment by thejakeyboy** [comment]
Oh, I think I just addressed this issue in my last comment. In any case, you can find one of my old course repos here: https://www.dropbox.com/sh/lyhqmuucackqdzf/AABqccpP1TSmttpmBz9HnS3-a?dl=0

**Comment by maabernethy** [comment]
@thejakeyboy I have made a [separate repo](https://github.com/maabernethy/jake-course-pages) with a course page template based on your old courses. Clone the repo and run it, and let me know what you think.

**Comment by maabernethy** [comment]
@thejakeyboy can you give me access to [this document](https://docs.google.com/document/d/1RiCCpPsqvg-7mLAn4JhrlTnCxgw3dVrIWZ0DS8-w9Gg/pub) so that I can convert it to markdown/HTML and put it into the course page template

**Comment by maabernethy** [comment]
Finished course pages template. Seen at [this repo](https://github.com/maabernethy/jake-course-pages)
