### ISSUE TITLE
mathjax script not working in some of my talks

### ISSUE THREAD

**Issue by thejakeyboy** [maabernethy/jake-academic-site#7]
I was informed by a student that my mathjax isn't always workign in my talks. For example: http://localhost:4000/slides/ec16_price_discovery/#1

At first I thought that maybe the mathjax host I was using was just no longer serving the js file. But it looks like that's not the issue (this still works: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML). Instead, there's some kind of a js bug I don't understand.

In any case, we should probably serve the mathjax script locally anyway. And the mathjax is working elsewhere (e.g. http://localhost:4000/slides/icml16_faster_convex/#8) so there's probably just some small bug.

**Comment by maabernethy** [comment]
<img width="1297" alt="screen shot 2018-07-24 at 2 39 47 pm" src="https://user-images.githubusercontent.com/4601777/43159133-7947bbe2-8f4f-11e8-8d96-753d64d7ba3a.png">

I fixed a few weeks ago and now that page is working for me...

**Comment by maabernethy** [comment]
Per phone conversation - it seems to be working so I will close this issue for now. If there is a problem, I can host mathjax locally in the future.
