### ISSUE TITLE
*ahem*

### ISSUE THREAD

**Issue by thejakeyboy** [maabernethy/jake-academic-site#8]
![bitmoji](https://render.bitstrips.com/v2/cpanel/fca599e4-a610-4d52-9782-218cd1e27305-6c601cbd-7fb9-4d02-966c-3de861df7620-v1.png?transparent=1&palette=1&width=246)

**Comment by maabernethy** [comment]
I am devoting tomorrow and friday completely to YOU :)

**Comment by maabernethy** [comment]
I will update throughout the day - stay tuned!
